export const CRIANZAS: Record<string, number> = {
  "GRANJA MASIA VICENT MAS": 1,
  "GRANJA INDUSTRIAL GANADERA": 1,
  "GRANJA GUINEU": 1,
  "GRANJA GIRALT": 1,
  "GRANJA RUBIO": 1,
  "GRANJA VENDRELL": 1,
  "GRANJA EL PI": 1,
  "GRANJA SINOGA": 1,
  "GRANJA CARTUJA 1": 1,
  "GRANJA ALFUSPI": 1,
  "C. JOSEP BOSCH": 21,
  "C. ROVIRA HOSTAL (S1/S2/S3)": 22,
  "C. RABES": 21,
  "C. CERCOS": 21,
  "C. COLLS": 22,
  "C. HUGUET": 19,
  "C. MIARNAU": 21,
  "C. ALBERTI NOVA": 13,
  "C. INGLES": 69,
  "C. TROBAT": 21,
  "C. VILANOVA RIBES": 20,
  "C. ESPASA": 21,
  "C. COSCOLLERA": 18,
  "C. LLOBET": 67,
  "C. MAIALS": 88,
  "C. MASSOS ENGREIX": 16,
  "C. FAYON 1": 22,
  "C. CEREALS 2 (C.BERNAUS) DESTETE": 34,
  "C. PROMOCIONES HOTELERAS": 9,
  "C. PERELLO GREGORI": 7,
  "C. GUARDIA": 8,
  "C. MARRO": 6,
  "C. PEDRERA": 5,
  "C. SARROCA": 6,
  "C. ERAS ALTAS": 3,
  "C. ZAIDIN DESTETE": 5,
  "C. RENANT RAMADERA": 2,
  "C. ARGILES": 3,
  "C. FALLET": 2,
  "C. OLIVA SEGARRA": 2,
  "C. GANADOS DOMINGO": 2,
  "C. GRANAPORK": 1,
}

export function getCrianza(granja: string): string {
  const c = CRIANZAS[granja]
  return c !== undefined ? String(c) : ""
}
